#!/bin/bash

# this script is used to control the download bandwidth of amule

if [[ $# == "1" ]] ;then
    new_limit=$1
    amulecmd -c "set bwlimit down ${new_limit}"
else
    amulecmd -c "status"
fi


