#!/bin/bash
#===============================================================================
#
#          FILE:  amt.sh
#
#         USAGE:  ./amt.sh
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  adaptee (), adaptee@gmail.com
#       COMPANY:  Open Source Corporation
#       VERSION:  1.0
#       CREATED:  06/05/10 23:18:48 CST
#      REVISION:  ---
#===============================================================================
head -n 1 ~/.aMule/history
tail -n 1 ~/.aMule/history

