#!/bin/bash
#===============================================================================
#
#          FILE:  chroot-ubuntu.sh
#
#         USAGE:  ./chroot-ubuntu.sh
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  adaptee (), adaptee@gmail.com
#       COMPANY:  Open Source Corporation
#       VERSION:  1.0
#       CREATED:  2010年01月15日 19时00分05秒 CST
#      REVISION:  ---
#===============================================================================

# Example
# command => chroot-gentoo
# distro  => gentoo
command=$(basename $0)
distro=${command#*-}

for item in {/boot,/dev,/dev/pts,/proc,/sys,/mnt/personal} ; do
    if [ -d "/mnt/${distro}/${item}" ] ; then
        sudo mount --bind "${item}" "/mnt/${distro}/${item}"
    fi
done

#sudo chname "${distro}" chroot "/mnt/${distro}"
sudo ~/bin/chname "${distro}" chroot "/mnt/${distro}"
#sudo ~/bin/chname "${distro}" chroot "/mnt/${distro}" "/bin/bash" -l


# do not forget the cleanup work
#for item in {/boot,/dev,/dev/pts,/proc,/sys,/mnt/personal} ; do
    #if [ -d "/mnt/${distro}/${item}" ] ; then
        #sudo umount -l "/mnt/${distro}/${item}"
    #fi
#done

