#!/bin/bash
#===============================================================================
#
#          FILE:  ed2k-debug.sh
#
#         USAGE:  ./ed2k-debug.sh
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  adaptee (), adaptee@gmail.com
#       COMPANY:  Open Source Corporation
#       VERSION:  1.0
#       CREATED:  09/16/10 11:33:31 CST
#      REVISION:  ---
#===============================================================================


echo "$(date): ed2k $@" >> ~/ed2k-debug.log

ed2k "$@"

