#!/bin/sh

#   DESCRIPTION:  start some vm in vbox

# when invoked by different symlink, $0 has different value
# eg: deepin -> VBoxManage stargvm deepin
#     910    -> VBoxManage stargvm 910

vmname="$(basename $0)"

VBoxManage startvm "${vmname}"
