#!/bin/bash
#===============================================================================
#
#          FILE:  umountiso
#
#         USAGE:  ./umountiso [isonamet]
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  adaptee (), adaptee@gmail.com
#       COMPANY:  Open Source Corporation
#       VERSION:  1.0
#       CREATED:  2009年12月27日 14时50分11秒 CST
#      REVISION:  ---
#===============================================================================


isoname=$( basename "$1" )
isonamewithoutextension=$(echo ${isoname%.*} )
mountpoint="${HOME}/Desktop/${isonamewithoutextension}"

if grep "$isoname" ~/.mtab.fuseiso > /dev/null ; then
    fusermount -u "${mountpoint}"
else
    # if not yet  mounted, do nothing
    fuseiso -p "$isoname" "$mountpoint"
fi
